script: bundle exec rspec -f json
rvm:
  - 2.1.0
notifications:
  webhooks: http://progress.flatironschool.com/submissions
cache: bundler
script: bundle exec rake db:migrate SINATRA_ENV=test; bundle exec rspec -f json
